### ISSUE TITLE
Как собрать книгу?

### ISSUE THREAD

**Issue by RareScrap** [mc-modding/mc-modding-book#29]
Хочу проверить как будут выглядеть мои изменения на сайте. Не могу собрать батниками, т.к. получаю
```bat
D:\Users\rares\Downloads\mc-modding-book>build-site.bat

D:\Users\rares\Downloads\mc-modding-book>node site/must-have/_tools/processes/build-must-have -local   && gulp move-must-have -local   && build-index   && build-books
module.js:549
    throw err;
    ^

Error: Cannot find module 'rimraf'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Users\rares\Downloads\mc-modding-book\site\must-have\_tools\processes\build-must-have.js:3:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by RareScrap** [comment]
Установил ноду, скачал зависимости и все таки собрал сайт. Но у него пропал весь css

**Comment by RareScrap** [comment]
@CMTV Вопрос еще актуален
